#设置服务器运行的端口号
server:
  port: 8084

#设置日志的打印
logging:
  level:
    com.liugang.warehousemangerment: DEBUG

spring:
  #设置数据源
  datasource:
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/liugang
  #设置thyemleaf模板引擎的配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML

#设置sql的映射文件来接口
mybatis:
  mapper-locations: classpath:mapperConfig/*.xml  #mapper映射xml文件的所在路径
  type-aliases-package: com.liugang.warehousemangerment.entity  #对应实体类的路径

